/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-11 21:28:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sample.core.domain.Mesa;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Mesa");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/scripts/bootstrap/css/bootstrap.min.css\" >\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/scripts-barcito.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logout.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/mesasDisponibles.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("  \t<script src=\"https://code.jquery.com/ui/1.14.1/jquery-ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar contextPath=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!--<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/style.css\" >-->\r\n");
      out.write("    <!--<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\t\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md navbar-dark bg-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("        <!-- icono o nombre -->\r\n");
      out.write("\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("          <img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/food_yellow.png\">\r\n");
      out.write("          <span class=\"text-warning\">Intelio</span>\r\n");
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("            \r\n");
      out.write("        <!-- boton del menu -->\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#menu\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("          <!-- elementos del menu colapsable -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"menu\">\r\n");
      out.write("          <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\t\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                Productos\r\n");
      out.write("              </a>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"dropdown-menu bg-secondary\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/plato.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/drink.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/dessert.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<li>   \r\n");
      out.write("                <li>\r\n");
      out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/menu.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("          <hr class=\"d-md-none text-white-50\">\r\n");
      out.write("\r\n");
      out.write("           <!-- enlaces redes sociales -->\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"navbar-nav  flex-row flex-wrap text-light\">\r\n");
      out.write("\r\n");
      out.write("           <li class=\"nav-item col-6 col-md-auto p-3\">\r\n");
      out.write("                <i class=\"bi bi-twitter\"></i>\r\n");
      out.write("                <small class=\"d-md-none ms-2\">Twitter</small>  \r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item col-6 col-md-auto p-3\">\r\n");
      out.write("              <i class=\"bi bi-github\"></i>\r\n");
      out.write("              <small class=\"d-md-none ms-2\">GitHub</small> \r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item col-6 col-md-auto p-3\">\r\n");
      out.write("              <i class=\"bi bi-whatsapp\"></i>\r\n");
      out.write("              <small class=\"d-md-none ms-2\">WhatsApp</small>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <li class=\"nav-item col-6 col-md-auto p-3\">\r\n");
      out.write("              <i class=\"bi bi-facebook\"></i>\r\n");
      out.write("              <small class=\"d-md-none ms-2\">Facebook</small>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("          \r\n");
      out.write("         <!--boton Informacion -->\r\n");
      out.write("\r\n");
      out.write("          <form class=\"d-flex\">\r\n");
      out.write("            <button class=\"btn btn-outline-warning d-none d-md-inline-block \" type=\"button\" id=\"btn-logout\">\r\n");
      out.write("\t\t\t\t<img alt=\"Brand\" src=\"");
      out.print(request.getContextPath());
      out.write("/icon/logout.png\">\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("          </form>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("     \r\n");
      out.write("        </div>  \r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"sec\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-light bg-light\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"#\">Mesas</a>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"card-group homeitem mt-4\"  id=\"contenedorMesas\"></div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"sec-pedidos\">\r\n");
      out.write("\t     <nav class=\"navbar navbar-light bg-light mt-4\">\r\n");
      out.write("\t\t\t  <a class=\"navbar-brand\" href=\"#\">Pedidos</a>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"recent_order\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<table id=\"boxPedidosSolicitados\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"25%\" class=\"center\">Titulo</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Precio</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Ver detalles</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"titulo\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"12%\" class=\"precio\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"12%\" class=\"detalles\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"sec-menus\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-light bg-light mt-4\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Productos</a>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"card-group homeitem mt-4\" id=\"menu-principal\">\r\n");
      out.write("\t\t\t<div class=\"card m-2\" >\r\n");
      out.write("\t\t\t\t<img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2023/05/31/11/15/fish-8031138_960_720.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Plato</h5>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">Platos disponibles</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosPlato\" class=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card m-2\" >\r\n");
      out.write("\t\t\t\t<img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2017/08/06/04/16/cupcake-2588646_1280.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Postres</h5>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">postres disponibls</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosPostre\" class=\"btn btn-primary\"  >Ir</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card m-2\" >\r\n");
      out.write("\t\t\t\t<img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2020/08/17/13/24/flower-5495384_1280.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Bebidas</h5>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">Bebida disponible</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosBebidas\" class=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"card m-2\" >\r\n");
      out.write("\t\t\t\t<img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2016/11/29/12/54/cafe-1869656_1280.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"card-title\">Menu</h5>\r\n");
      out.write("\t\t\t\t\t<p class=\"card-text\">menu disponibles</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print( request.getContextPath());
      out.write("/leerDatosMenu\" class=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/bootstrap/js/bootstrap.bundle.min.js\" ></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
