/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-13 13:42:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.sample.core.domain.Mesa;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sample.core.domain.Mesa");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Home Pizzeria</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap y scripts -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/scripts/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/scripts-barcito.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logout.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/mesasDisponibles.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.14.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var contextPath = \"");
      out.print(request.getContextPath());
      out.write("\r\n");
      out.write("\t\";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Pacifico&family=Roboto&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Roboto', sans-serif;\r\n");
      out.write("\tbackground-color: #fff8e1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand span {\r\n");
      out.write("\tfont-family: 'Pacifico', cursive;\r\n");
      out.write("\tfont-size: 1.5rem;\r\n");
      out.write("\tcolor: #d32f2f !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\tbox-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("\tcolor: white !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\tbox-shadow: 0 0 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("\tmax-width: 400px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .btn-primary {\r\n");
      out.write("\tbackground-color: #ffc107;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card .btn-primary:hover {\r\n");
      out.write("\tbackground-color: #ff9800;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-light.bg-light, .navbar-light {\r\n");
      out.write("\tbackground-color: #fef3e3 !important;\r\n");
      out.write("\tborder-bottom: 2px solid #ffc107;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-title {\r\n");
      out.write("\tfont-family: 'Pacifico', cursive;\r\n");
      out.write("\tcolor: #d32f2f;\r\n");
      out.write("\tmargin-top: 2rem;\r\n");
      out.write("\tmargin-bottom: 1rem;\r\n");
      out.write("\tfont-size: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-title {\r\n");
      out.write("\tcolor: #d32f2f;\r\n");
      out.write("\tfont-family: 'Pacifico', cursive;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-img-top {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 250px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tbackground-color: #fff8e1;\r\n");
      out.write("\tborder-top-left-radius: 20px;\r\n");
      out.write("\tborder-top-right-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-group.homeitem {\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid px-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navbar -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-md navbar-dark\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"> <img alt=\"Brand\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/food_yellow.png\"\r\n");
      out.write("\t\t\t\t\theight=\"30\"> <span>Intelio</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-bs-toggle=\"collapse\" data-bs-target=\"#menu\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"menu\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav me-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-bs-toggle=\"dropdown\">Productos</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu bg-secondary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><img alt=\"Plato\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/plato.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><img alt=\"Bebida\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/drink.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><img alt=\"Postre\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/dessert.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\"><img alt=\"Menú\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/menu.png\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Redes sociales -->\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav flex-row text-light\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item p-2\"><i class=\"bi bi-twitter\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item p-2\"><i class=\"bi bi-github\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item p-2\"><i class=\"bi bi-whatsapp\"></i></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item p-2\"><i class=\"bi bi-facebook\"></i></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Logout -->\r\n");
      out.write("\t\t\t\t\t<form class=\"d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-outline-warning\" type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"btn-logout\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"Logout\"\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/icon/logout.png\">\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Secciones especiales por rol -->\r\n");
      out.write("\t\t<div class=\"solo-admin\" style=\"display: none;\">Botón solo para\r\n");
      out.write("\t\t\tAdmin</div>\r\n");
      out.write("\t\t<div class=\"solo-cocinero\" style=\"display: none;\">Vista de\r\n");
      out.write("\t\t\tcocina</div>\r\n");
      out.write("\t\t<div class=\"solo-delivery\" style=\"display: none;\">Panel de\r\n");
      out.write("\t\t\tdelivery</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/mostrarPorRol.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Mesas -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Pedidos -->\r\n");
      out.write("\t\t<section id=\"sec-pedidos\">\r\n");
      out.write("\t\t\t<h2 class=\"section-title\">Pedidos</h2>\r\n");
      out.write("\t\t\t<div class=\"recent_order\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered bg-white\">\r\n");
      out.write("\t\t\t\t\t<thead class=\"table-warning text-center\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Título</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Precio</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Ver detalles</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"detalles\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Menú principal -->\r\n");
      out.write("\t\t<section id=\"sec-menus\">\r\n");
      out.write("\t\t\t<h2 class=\"section-title\">Productos</h2>\r\n");
      out.write("\t\t\t<div class=\"d-flex flex-wrap justify-content-start\"\r\n");
      out.write("\t\t\t\tid=\"menu-principal\" style=\"width: 100%; gap: 10px;\">\r\n");
      out.write("\t\t\t\t<div class=\"card\" style=\"margin-left: 0;\">\r\n");
      out.write("\t\t\t\t\t<img class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"http://bostonschihuahua.com.mx/wp-content/uploads/2015/09/pizzas-hawaiana-2x.jpg\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Pizza\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t<h5 class=\"card-title\">Pizza</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">Pizzas disponibles</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/LeerDatosPizza\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/scripts/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
