/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-06-12 01:32:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.usuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("           \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Login</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" \r\n");
      out.write("\t      integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" \r\n");
      out.write("\t      crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Fuente divertida tipo pizzería -->\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Pacifico&family=Roboto&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t    height: 100vh;\r\n");
      out.write("\t\t    margin: 0;\r\n");
      out.write("\t\t    display: flex;\r\n");
      out.write("\t\t    justify-content: center;  /* Centrar horizontalmente */\r\n");
      out.write("\t\t    align-items: center;      /* Centrar verticalmente */\r\n");
      out.write("\t\t    font-family: 'Roboto', sans-serif;\r\n");
      out.write("\t\t    background-color: #fff3e0; /* Fondo cálido */\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.container {\r\n");
      out.write("\t\t    background-color: rgba(255, 255, 255, 0.95);\r\n");
      out.write("\t\t    padding: 30px;\r\n");
      out.write("\t\t    border-radius: 30px;\r\n");
      out.write("\t\t    max-width: 400px;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t    box-shadow: 0 0 15px rgba(0, 0, 0, 0.3);\r\n");
      out.write("\t\t    color: #333;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\th1 {\r\n");
      out.write("\t\t    font-family: 'Pacifico', cursive;\r\n");
      out.write("\t\t    color: #d32f2f;\r\n");
      out.write("\t\t    text-align: center;\r\n");
      out.write("\t\t    margin-bottom: 25px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tlabel {\r\n");
      out.write("\t\t    font-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.btn-pizza {\r\n");
      out.write("\t\t    background-color: #ffc107;\r\n");
      out.write("\t\t    color: #000;\r\n");
      out.write("\t\t    border: none;\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.btn-pizza:hover {\r\n");
      out.write("\t\t    background-color: #ff9800;\r\n");
      out.write("\t\t    color: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar contextPath = '");
      out.print(request.getContextPath());
      out.write("';\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/login.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1>Ingresar Usuario</h1>\r\n");
      out.write("\t\t<form class=\"form\" id=\"Login\">\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"usuario\">Usuario</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"usuario\" name=\"usuario\" placeholder=\"Ingresa tu usuario\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<label for=\"password\">Contraseña</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" placeholder=\"Ingresa tu contraseña\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-pizza\" id=\"btn-login\">Entrar 🍕</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
